### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by DarkPheonix2122** [TheShadowGamer/Invite-Manager#1]
can i make a small dashboard for configuring the bot easier, it would help a lot.

**Comment by IeuanGol** [comment]
Of course, you can!

**Comment by TheShadowGamer** [comment]
Of course! I do agree that it would help some people configure the bot. What’s your discord by the way?

**Comment by DarkPheonix2122** [comment]
DarkPheonix#0124

**Comment by DarkPheonix2122** [comment]
Can I get write access to the github?

**Comment by IeuanGol** [comment]
Create a PR

**Comment by TheShadowGamer** [comment]
^

**Comment by TheShadowGamer** [comment]
So just make the changes to your fork, and then create a pull request.

**Comment by DarkPheonix2122** [comment]
k

**Comment by DarkPheonix2122** [comment]
can yall make a new branch, like a dev branch, this is still kinda being worked on, and I dont want to mess up the bot.

**Comment by IeuanGol** [comment]
It can be merged into a dev branch

**Comment by IeuanGol** [comment]
(TheShadow will do this; you won't have to worry about anything :))

**Comment by TheShadowGamer** [comment]
Done

**Comment by DarkPheonix2122** [comment]
Okay! the dash is mostly done, i will add you to to repository, because i was dumb and didnt just add it into my fork

**Comment by TheShadowGamer** [comment]
Can you just move the code over to your fork?

**Comment by DarkPheonix2122** [comment]
gud point

**Comment by TheShadowGamer** [comment]
Just make a pull request whenever you are finished.

**Comment by DarkPheonix2122** [comment]
srry it took so long

**Comment by IeuanGol** [comment]
No worries. :) 

We can now discuss this on the pull request (#2)
