### ISSUE TITLE
Slash Commands

### ISSUE THREAD

**Issue by TNRXD** [TheShadowGamer/Invite-Manager#13]
Slash Commands Aren't Working, This is My console.
![image](https://user-images.githubusercontent.com/70138311/117197845-f76ffd00-adf0-11eb-8974-3e0d85811084.png)
Can I Please Get Some Help? Thanks.

- NameFlix.

**Comment by Lorange7** [comment]
before you post issues look at previous unsolved issues this has already been stated

**Comment by TheShadowGamer** [comment]
This was fixed in the discord support server.
