### ISSUE TITLE
Welcome Channel

### ISSUE THREAD

**Issue by AlphonsoJuice** [TheShadowGamer/Invite-Manager#15]
So, when I was looking into config file I found that we have to define the welcome channel ID which led me to thought that this feature may make the bot for personal uses and not for public. Do you have any ideas how to manually setup the welcome channel ID within a server so each server that has my bot can use it?

**Comment by TheShadowGamer** [comment]
You’ll need to code in a database for config.
Then have a setup command. 
The setup command saved the welcome channel, and in the bot, wherever it calls on client.config.welcomeChannel, you change it to pull from your database.
